spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: apna-bazaar
  web:
    error:
      include-message: always
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-3.1-flash-lite
  base-url: https://generativelanguage.googleapis.com
